[package]
name = "fvm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0.47"
thiserror = "1.0.30"
num-traits = "0.2"
derive_builder = "0.10"
ahash = "0.7"
num-derive = "0.3.3"
cid = { version = "0.8.2", default-features = false, features = ["serde-codec"] }
multihash = { version = "0.16.1", default-features = false, features = ["identity"] }
fvm_shared = { path = "../shared", features = ["crypto"] }
ipld_hamt = { path = "../ipld/hamt"}
ipld_amt = { path = "../ipld/amt"}
serde = { version = "1.0", features = ["derive"] }
serde_tuple = "0.5"
serde_repr = "0.1"
lazy_static = "1.4.0"
derive-getters = "0.2.0"
derive_more = "0.99.17"
replace_with = "0.1.7"
filecoin-proofs-api = { version = "11", default-features = false }
rayon = "1"
num_cpus = "1.13.0"
log = "0.4.14"
byteorder = "1.4.3"
anymap = "0.12.1"

[dependencies.wasmtime]
version = "0.33.0"
default-features = false
features = ["cranelift", "pooling-allocator", "parallel-compilation"]

[features]
default = ["opencl"]
opencl = ["filecoin-proofs-api/opencl"]
cuda = ["filecoin-proofs-api/cuda"]
